### ISSUE TITLE
Serialization should not be limited to JSON (HTTPS-1)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#10]
Currently, section 3.2.1 states that JSON serialization must be _used_. Suggest that the language be changed to say that JSON serialization must be _supported_, so that there are requirement to support JSON for conformance but other serializations aren't precluded.

**Comment by sparrell** [comment]
I disagree with changing 'used' to 'supported'. More importantly I disagree with implying using another serialization would be considered in compliance with the specification. I do not consider other serializations to be 'extensions'. With the specifications as they exist today, you are in compliance only if you use JSON.

I am not against adding other serializations. It's not clear to me whether an additional serialization would be included in this specification or in a new transport specification (might depend on use cases and if the two ever need to interwork). But until such other serializations exist in a specification I am against wording that implies they are standard.

**Comment by jmbrule** [comment]
must be 'Supported' ensures interoperabilty, must be 'used' precludes other serializations.   Seems straight forward enough to me.  Also, this is a transfer spec, that is this spec is focused on the transfer of the messages.  How it is serialized within the payload is beyond the transfer spec.  Forcing whatever in the payload violates separation of concerns.

**Comment by davaya** [comment]
I strongly oppose designing a standard that does not support backwards compatibility.   I vote for saying that the current serialization MUST be supported.

A 1.0 implementation that supports feature A is interoperable with a 1.2 implementation that supports features A and B.    A 1.0 standard that says feature A MUST be used prohibits feature B from ever being developed -- if two 1.2 implementations could negotiate use of feature B, they are noncompliant with standard 1.0 if they actually use B.

**Comment by sparrell** [comment]
Wrt @jmbrule comment on defining supported and used - I did not know that was their meaning. If that is intent then more words should be used to explain the subtlety. 

However I still disagree that "used" precludes adding other serializations in future. Until the other serialization exists, and the interworking is defined (eg how to negotiate which to use) then we can't say whether instantiations of current specification will work with instantiations of new specification. I am still against allowing something not yet in the specification being allowed to be considered conformant. If we want other serializations, start discussing them and how to add them and we'll see if it becomes a 1.1 (ie backwards compatible) or a 2.0 (ie not backwards compatible). And once we add 'feature B' (of @davaya comment) we can word it correctly and "1.2" will supercede "1.0" anyway. What word we use in this paragraph won't change how people build it and it's future proofing. What matters is the conformance clauses. In 1.0 do you intent to allow non-JSON to be conformant? I vote no for 1.0. I'll vote yes for whatever other ones we add in once they are added in. But I do not think this is an area where vendors can do extensions on their own because it will be unlikely they do it in a way that will interwork with other vendors. Sticking to  only specified serializations will encourage specifying these new serializations that are apparently the cause of this thread.

**Comment by dlemire60** [comment]
Now have a PR (#29) with proposed changes to 3.2.1.  I don't think there's any intent to allow other serializations to be considered conformant.  The conformance section says:

> A conformant implementation of this transfer specification MUST:
>  - Support JSON serialization as specified in Section 3.2.1
 
and the the HTTPS implementation of OpenC2 message content is 

> "JSON verbose serialization of OpenC2 commands and responses carried in the HTTP message body"

and I've updated the PR to remove verbose there (already removed it in 3.2.1).

**Comment by dlemire60** [comment]
This issue may be related to Language Specification [issue 153](https://github.com/oasis-tcs/openc2-oc2ls/issues/153).

**Comment by jmbrule** [comment]
In the context of this issue;  if a product supports JSON serialization and is capable of 'interworking' with other products that are conformant with the spec then what is the issue?  
The concern seems to be that if a product also supports another serialization (such as CBOR) then it will no longer be able to 'interwork'?  I do not understand the mechanism such that if a product supports an additional serialization, then it is no longer conformant.

**Comment by jmbrule** [comment]
Discussed at great length during the IC-SC telecon that took place on 1/2/2019, the IC SC recommends wording to ensure that other serializations are not precluded and ensure that if a product implements other transfer specs, then it can still be conformant with the https spec

**Comment by dlemire60** [comment]
Given that there's an open [pull request](https://github.com/oasis-tcs/openc2-impl-https/pull/29) for this, it would be helpful if we could move beyond general comments and provide feedback on the proposed wording. I believe it accomplishes the goal of JSON being required for conformance and other serializations not precluded, but others might disagree.

**Comment by dlemire60** [comment]
This topic was discussed at the January 2019 F2F and the PR language was presented. The major concern raised was whether this opened a window for products that didn't provide JSON messaging for interoperability could still be deemed conformant. After examine the proposed wording, the F2F consensus was in favor of this change.

**Comment by dlemire60** [comment]
Merged pull request.
