### ISSUE TITLE
"transport independent" (HTTPS-20)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#45]
Duncan Sparrell [wrote](https://lists.oasis-open.org/archives/openc2/201812/msg00048.html): 

> "The message layer provides a content- and transport-independent mechanism" is incorrect if the correlation-id is necessary for the cancel command. Assuming the command-id is not added back in the language spec, then "transport-independent" should be removed in this spec

**Comment by jmbrule** [comment]
Do not agree with this comment.  The exchange of primitives (between layers) is consistent with (in fact necessary) for the OSI model to function so I do not agree with the conclusion that the use of the correlation-id binds OpenC2 to a particular transport.  
This could be a case of misinterpretation.  I interpret 'transport' agnostic as being independent of a _particular_ transport layer.  Having said, that, openc2 still requires a transfer, transport, internet, data link and physical layer so agree that it cannot be 'independent' of the other layers, but submit that we should strive for being agnostic of the transport layer. 
Consider changing to 'transport agnostic' rather than 'transport independent'?

**Comment by dlemire60** [comment]
Based on the agreement to add command-id back into the OpenC2 command body, Duncan Sparrell has stated he's withdrawing his comment.  However, I think there's virtue in considering @jmbrule's suggestion of "transport-agnostic" in place of "transport-independent.

**Comment by davaya** [comment]
I don't agree that "A is independent of B" means that nothing requires B to exist.

The fact that messages are being transported means that there MUST be a transport mechanism.

Stating that messaging is transport-independent does not get rid of the separate requirement for a transport mechanism to exist - it just says that messaging is unaffected by how transport is done.

And as Toby would remind us, saying that software is platform-independent (http://www.businessdictionary.com/definition/platform-independent.html) does not imply that software can run without any platform.

But as independent and agnostic are synonyms in this context, I don't object to using agnostic.
