### ISSUE TITLE
Remove "backward" scenario (AKA polling) (HTTPS-23)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#48]
Duncan Sparrell [wrote](https://lists.oasis-open.org/archives/openc2/201812/msg00051.html):
> I have several issues with the "backwards" scenarios where the OpenC2 Consumer (eg the IoT device) controls the communications instead of the OpenC2 Producer (eg the security orchestrator) and would propose to delete these in this initial version of OpenC2.
>
> OpenC2 is new and I think we are making unnecessarily-complicated scenarios for version 1.0. This "backwards" scenario greatly complicates understanding this specification.

**Note:** Addition detail in the linked email.

**Comment by jmbrule** [comment]
In agreement with this comment.  The polling scenario is in fact atypical, and this early in the lifecycle of the specification I am not convinced that we need to introduce this level of complexity.  If we were 'constrained' to only one transfer protocol and it had to be all things, one could make the case, however I submit that we should investigate other transfer mechanisms (rather than make the existing transfer mechanism more complex) 
Not going to dig my heels one way or the other, but in general agreement with the reviewer

**Comment by dlemire60** [comment]
I believe the following changes are needed to implement this comment:

- Edit section 2.1 to remove references to configurations where the OpenC2 Producer is the listener.
- Delete figure 3
- Delete sections 2.4, 3.4, and 3.5
- Delete references to section 3.4 in the conformance list in section 4.1
- Remove section B.2 from Annex B.
- Probably delete reference to RFC6546 (referenced in text in 2.1)

**Comment by jmbrule** [comment]
Based on the IC-SC telecon that took place on 1/2/2019, the IC SC recommends removing the polling scenario from this spec

**Comment by dlemire60** [comment]
This was discussed at the January 2019 F2F and a summary of the associated changes was presented.  The consensus of the F2F meeting was to approve this change, with no one speaking against it. The prevailing opinion was the the polling scenario adds significant complexity, and should be deferred to future versions if/when substantiated by use cases.

**Comment by dlemire60** [comment]
Proposed change language now available in PR #61

**Comment by dlemire60** [comment]
Per consensus at the 6 February IC-SC meeting, I'm applying PR #61 and closing this issue.
