### ISSUE TITLE
Possible misconception in Section 1.8 Suitability

### ISSUE THREAD

**Issue by Vasileios-Mavroeidis** [oasis-tcs/openc2-impl-https#97]
Section 1.8 in the HTTPS transfer spec elaborates on the requirements for operational environments that want to implement OpenC2 over HTTPS.

The third bullet point remarks that:  "The overhead of HTTPS is acceptable (e.g., multiple OpenC2 Command / Response exchanges can be passed through a single HTTPS connection)."
 
The above sentence indicates that the overhead **OF** https is derived, among other, from multiple OpenC2 commands through a single HTTPS connection.

The overhead of HTTPS per se is derived from the introduction of TLS over HTTP.  It requires more handshakes and as a result, there is an increase in the negotiation time and resources used for that.

Multiple OpenC2 commands over a single HTTPS connection  -  this is related to bandwidth and throughput.

Finally, the example mentions a single HTTPS connection. Basically that means that the negotiation happens once, reducing any overhead multiple connections and their negotiation would introduce.

A possible solution to the aforementioned would be to remove the example in the parenthesis.

**Comment by dlemire60** [comment]
Looking at that text again, I see multiple issues:

1. The one raised above by @Vasileios-Mavroeidis 
2. The phrase "a connection initiated by either Producer or Consumer" should have had the words "or Consumer" struck when the polling option was eliminated; in the current spec connections are only initiated by Producers
3. Possibly some words are needed regarding one-time vs. re-used connections. 

A related question is whether the specification should allow for use of HTTP (non-S) in a testing environment, since at the plug fest we had a complicated mix of various sources of certificates, some implementations that could operate without TLS and others that couldn't, etc.

**Comment by dlemire60** [comment]
@Vasileios-Mavroeidis -- can you look at the Section 1.8 changes in PR #106 and see if they address your concerns?

**Comment by dlemire60** [comment]
This issue was addressed by PR #106 and is now closed.
